//
//  Particle.cpp
//  SDL Test
//
//  Created by Abdul Hoque Habib on 04/11/2024.
//

#include "Particle.hpp"
#include <stdlib.h>
#include <math.h>

Particle::Particle() : m_x(0), m_y(0) {
    
    constructorFunc(); //we do this as we want to reinitalise the particles with more random values by calling it when it reaches the edge of the screen. We wouldnt be able to do this if the direction and speed was set in the constructor as it only executes when the object is first created.
    
    
}

void Particle::constructorFunc() {
   
    m_x = 0; //these set all the particles in the middle of the screen
    m_y = 0;
    
    
    m_direction = (2 * M_PI * rand())/RAND_MAX; //rand()/RANDMAX returns a number between 0.0 and 1.0. 2M_PI is just 2π, and we use this as 2π radians is the measurement for the angle for the whole circumference of the circle. So now we have a range from 0 to 2π, which is equivalent to 360 degrees. each particle would now have their own set angle and speed for their entire lifetime and this is set to m_x and m_y in update()
    m_speed = (0.07 * rand())/RAND_MAX;
    //returns value between 0.0 and 1.0. Multiplying by a constant, like 0.07 scales range between 0.0 and 0.07
    
    m_speed = m_speed * m_speed; //square the speed to most particles moving slowly and a few moving much faster. Without squaring, the speed values would follow a uniform distribution between 0 and 1. By squaring, smaller speeds become more frequent (e.g. 0.1^2 = 0.01) and larger speeds are less likely, so more partices stay closer to gether and some spread out due to its faster speed- creating more of an explosion effect
    
    
    //prior stage of 3. (double)rand()/RAND_MAX; //rand() is a function that generates a random positive float betwen 0 and RAND_MAX and RAND_MAX represents the maximum value rand() can return, so dividing them will give a value between 0 and 1 (inclusive).
    //prior stage of 3.  //m_x = (2.0 * rand()/RAND_MAX) - 1; //we want the starting co-ordinates of the particle to be on a cartesian plane, where the range of both the x and y value is -1 to 1. As rand() returns a value between 0 and RAND_MAX, 2 * rand() creates a value ranging from 0 to 2*RAND_MAX (e.g. if max value of RAND_MAX was generated, like 32767, it would be *2, doubling the range.) The result of this is then divided by RAND_MAX giving a range between 0.0 to 2.0. SUbtracting the entire reuslt by 1 shifts the range to -1 to 1. E.g. lets say the max value was generated by rand(), so 32767. We multiplt by 2 to get 65534 and divide this by 32767 to get 2. We then subtract 1 to get 1, which is in our max value.
    //prior stage of 3. m_y = (2.0 * rand()/RAND_MAX) - 1; //2 * rand() / RAND_MAX performs integer math, which truncates any decimal points in the result so we need to perform a float division
    
    //3. m_xspeed = 0.001 * ((( 2.0 * rand())/RAND_MAX) - 1); //multiplying by 2.0 increases the range from 0 to 1 to 0 to 2. Then we subtract one to get a range from -1 to 1. Then we multiply this by 0.01 which determines how far each particle will move to get a range from -0.01 to 0.01. This is mapped to the screen's pixel range in main.
    //3. m_yspeed = 0.001 * (((2.0 * rand())/RAND_MAX) - 1);
    
}

void Particle::updatePositionEachParticle(int interval) { //
    
    //1. //const double xspeed = ((0.001 * rand())/RAND_MAX); //stores a random number in xspeed between 0 and 1. We force it to do double division so it doesnt truncate as it would if it did int division. However, this only ever gives a positive number, and we want the the particles to move in random positions throughout the screen, not just to the right. So we must modify this to give a range from a negative to a positive number. This is mapped to the screen's pixel range in main.
    //const double yspeed = ((0.001 * rand())/RAND_MAX);
    
    //2. //const double xspeed = 0.01 * ((( 2.0 * rand())/RAND_MAX) - 1); //we increase the range from 0 to 1 to 0 to 2. Then we subtract one to get a range from -1 to 1. Then we multiply this by 0.01 to get a range from -0.01 to 0.01. This is mapped to the screen's pixel range in main.
    //const double yspeed = 0.01 * (((2.0 * rand())/RAND_MAX) - 1);
    
    //2. //m_x += xspeed;     //same as m_x = xspeed + 0.01;
    //2. //m_y += yspeed;     //same as m_y = yspeed + 0.01;
    //When we call this function, the x and y values of each pixel will be added to speed, changing their position every iteration
    
    
    //what happens here though is each particle moves by a certain amount (in the range) each time- giving a random and fly looking animation. We want a more smoother one, so we have to give each specific particle its own speed and direction for its entire lifespan. To do this we can assign these attributes in the Particle constructor instead, as the constructor is executed every time a Particle object is made/initialised- allowing us to assign the attributes to each Particle object
    
   //3. //m_x += m_xspeed;
    //3. //m_y += m_yspeed;
    
    /*3. //if(m_x < -1 || m_x >= 1.0) { //When a particle hits the range for the x value (either side of the screen), it reverses the direction by negating
     
        m_xspeeds.
        m_xspeed = -m_xspeed;
    }
        
    if(m_y < -1 || m_y >= 1.0) { // this range is mapped in main to the Screen pixel range. //When a particle hits the range for the y value (either top ot bottom of the screen), it reverses the direction by negating m_xspeeds.
        m_yspeed = -m_yspeed;
     //this means no matter where the particle hits the screen, it will reverse its direction and 'bounce' off.
 */
    
   
    
    //1. = just the explanation of the stage begore 2.
    //2. = setting the speed and direction in update(), so all partciles have the same values applied each frame.
    //3. = speed and direction has been set in constructor, so each particle object has its own speed and direction. When we say speed and direction, is means that in 0.001 * ((( 2.0 * rand())/RAND_MAX) - 1), 0.001 controls the 'speed' as this decreases the value and so how far the particle can move. 2.0 * rand())/RAND_MAX) - 1 gives a random value between -1 to 1, which is its direction. Together they give where a co-ordinate the particle moves each frame.
    
    double xdistance = m_speed * cos(m_direction); //m_speed and m_direction are defined in the constructor
    double ydistance = m_speed * sin(m_direction);
    //This maps polar co-ordiantes to cartesian ones using trig (storing them in xdistance and ydistance so we can convert/map it to pixel grid co-ords in main.
    //m_direction represents the angle of the triangle- in radians the particle will move- measured from the origin.
    //m_speed represents the hypotenuse of a right triangle, showing the particle's distance covered or 'speed'. So multiplying is doing cos() * hyp = Adj, which gives us the horizontal component/x value- stored in xdistance
    //for ydistance: m_speed represents hyp, showing particles distance it will move. So doing sin() * hyp = Opp, which gives us the vertical component/y value- stored in ydistance
    //This is easily represented in the unit circle.

    
    m_x += xdistance * interval; //Multiplying by interval ensures that particles move further when more time has elapsed (i.e computer is slower) and less when less time has elapsed (i.e. computer is faster) between each time update() is called. Without interval, particle motion would vary based on how fast the program executes each loop, which is inconsistent with diff computers
    m_y += ydistance * interval;
    //we now have the horizontal and vertical components for a single particle stored in m_x and m_y which will update every frame. As the randomly generated values are set for each object in the constructor- each particle will move in their set pattern for its lifetime.
    
    m_direction = m_direction + interval * 0.0003; //m_direction: Represents the angle (in radians) of the particle's movement. interval: Indicates the time elapsed since the last update, ensuring the change in direction scales with the time step. 0.0003: Acts as a constant rate of change, controlling how quickly the direction evolves. This means the angle for the direction of the particles changes over time, creating a spiraling effect, like an explosion imploding in of itself. To stop this, we can set the constant to a smaller number to reduce the spiralling effect
    
    //  //If this were in the constructor, xspeed, yspeed,  would be fixed from the start for each particle, giving each particle a constant direction and speed for its lifetime, which is too static and wont give the explosion effect

    
    if((m_x < -1 || m_x >= 1.0) || (m_y < -1 || m_y > 1)) {
        constructorFunc(); //everytime a particle reaches the edge, this func will be called and the particle will be reset to the middle and then assigned random direction and speed again
    }
    
    
    if(rand() < RAND_MAX/100) { //f(rand() < RAND_MAX/100) generates a random integer and checks if it is less than 1% of RAND_MAX (the maximum value returned by rand()). If this condition is true, it calls constructorFunc(). This means that with a probability of 1%, the constructorFunc() will be executed, potentially initializing or modifying some behavior of a particle or object in the program (such as creating a new particle or changing its state). This introduces randomness to the behaviour.
        //constructorFunc();
    }
    
    /*if(m_x < -1 || m_x >= 1.0) {
        m_speed = -m_speed;
    }
        
    if(m_y < -1 || m_y >= 1.0) {
        m_speed = -m_speed;
    
     */
    
}
